/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as CommandsRouteImport } from './routes/commands'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VTokenRouteImport } from './routes/v.$token'
import { Route as LinkTokenRouteImport } from './routes/link.$token'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramImportRouteImport } from './routes/api/public/telegram/import'
import { Route as ApiPublicHooksLeaderboardBroadcastRouteImport } from './routes/api/public/hooks/leaderboard-broadcast'
import { Route as ApiPublicHooksDripRouteImport } from './routes/api/public/hooks/drip'
import { Route as ApiPublicHooksDbExportRouteImport } from './routes/api/public/hooks/db-export'
import { Route as ApiPublicHooksBroadcastRouteImport } from './routes/api/public/hooks/broadcast'
import { Route as ApiPublicHooksAutodeleteRouteImport } from './routes/api/public/hooks/autodelete'
import { Route as ApiPublicHooksAutoBackupRouteImport } from './routes/api/public/hooks/auto-backup'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandsRoute = CommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VTokenRoute = VTokenRouteImport.update({
  id: '/v/$token',
  path: '/v/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkTokenRoute = LinkTokenRouteImport.update({
  id: '/link/$token',
  path: '/link/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramImportRoute = ApiPublicTelegramImportRouteImport.update({
  id: '/api/public/telegram/import',
  path: '/api/public/telegram/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksLeaderboardBroadcastRoute =
  ApiPublicHooksLeaderboardBroadcastRouteImport.update({
    id: '/api/public/hooks/leaderboard-broadcast',
    path: '/api/public/hooks/leaderboard-broadcast',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDripRoute = ApiPublicHooksDripRouteImport.update({
  id: '/api/public/hooks/drip',
  path: '/api/public/hooks/drip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDbExportRoute = ApiPublicHooksDbExportRouteImport.update({
  id: '/api/public/hooks/db-export',
  path: '/api/public/hooks/db-export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBroadcastRoute = ApiPublicHooksBroadcastRouteImport.update({
  id: '/api/public/hooks/broadcast',
  path: '/api/public/hooks/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAutodeleteRoute =
  ApiPublicHooksAutodeleteRouteImport.update({
    id: '/api/public/hooks/autodelete',
    path: '/api/public/hooks/autodelete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoBackupRoute =
  ApiPublicHooksAutoBackupRouteImport.update({
    id: '/api/public/hooks/auto-backup',
    path: '/api/public/hooks/auto-backup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/commands': typeof CommandsRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/link/$token': typeof LinkTokenRoute
  '/v/$token': typeof VTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/hooks/auto-backup': typeof ApiPublicHooksAutoBackupRoute
  '/api/public/hooks/autodelete': typeof ApiPublicHooksAutodeleteRoute
  '/api/public/hooks/broadcast': typeof ApiPublicHooksBroadcastRoute
  '/api/public/hooks/db-export': typeof ApiPublicHooksDbExportRoute
  '/api/public/hooks/drip': typeof ApiPublicHooksDripRoute
  '/api/public/hooks/leaderboard-broadcast': typeof ApiPublicHooksLeaderboardBroadcastRoute
  '/api/public/telegram/import': typeof ApiPublicTelegramImportRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/commands': typeof CommandsRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/link/$token': typeof LinkTokenRoute
  '/v/$token': typeof VTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/hooks/auto-backup': typeof ApiPublicHooksAutoBackupRoute
  '/api/public/hooks/autodelete': typeof ApiPublicHooksAutodeleteRoute
  '/api/public/hooks/broadcast': typeof ApiPublicHooksBroadcastRoute
  '/api/public/hooks/db-export': typeof ApiPublicHooksDbExportRoute
  '/api/public/hooks/drip': typeof ApiPublicHooksDripRoute
  '/api/public/hooks/leaderboard-broadcast': typeof ApiPublicHooksLeaderboardBroadcastRoute
  '/api/public/telegram/import': typeof ApiPublicTelegramImportRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/commands': typeof CommandsRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/link/$token': typeof LinkTokenRoute
  '/v/$token': typeof VTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/hooks/auto-backup': typeof ApiPublicHooksAutoBackupRoute
  '/api/public/hooks/autodelete': typeof ApiPublicHooksAutodeleteRoute
  '/api/public/hooks/broadcast': typeof ApiPublicHooksBroadcastRoute
  '/api/public/hooks/db-export': typeof ApiPublicHooksDbExportRoute
  '/api/public/hooks/drip': typeof ApiPublicHooksDripRoute
  '/api/public/hooks/leaderboard-broadcast': typeof ApiPublicHooksLeaderboardBroadcastRoute
  '/api/public/telegram/import': typeof ApiPublicTelegramImportRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/commands'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/link/$token'
    | '/v/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/health'
    | '/api/public/hooks/auto-backup'
    | '/api/public/hooks/autodelete'
    | '/api/public/hooks/broadcast'
    | '/api/public/hooks/db-export'
    | '/api/public/hooks/drip'
    | '/api/public/hooks/leaderboard-broadcast'
    | '/api/public/telegram/import'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/commands'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/link/$token'
    | '/v/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/health'
    | '/api/public/hooks/auto-backup'
    | '/api/public/hooks/autodelete'
    | '/api/public/hooks/broadcast'
    | '/api/public/hooks/db-export'
    | '/api/public/hooks/drip'
    | '/api/public/hooks/leaderboard-broadcast'
    | '/api/public/telegram/import'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/commands'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/link/$token'
    | '/v/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/health'
    | '/api/public/hooks/auto-backup'
    | '/api/public/hooks/autodelete'
    | '/api/public/hooks/broadcast'
    | '/api/public/hooks/db-export'
    | '/api/public/hooks/drip'
    | '/api/public/hooks/leaderboard-broadcast'
    | '/api/public/telegram/import'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommandsRoute: typeof CommandsRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  LinkTokenRoute: typeof LinkTokenRoute
  VTokenRoute: typeof VTokenRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicHooksAutoBackupRoute: typeof ApiPublicHooksAutoBackupRoute
  ApiPublicHooksAutodeleteRoute: typeof ApiPublicHooksAutodeleteRoute
  ApiPublicHooksBroadcastRoute: typeof ApiPublicHooksBroadcastRoute
  ApiPublicHooksDbExportRoute: typeof ApiPublicHooksDbExportRoute
  ApiPublicHooksDripRoute: typeof ApiPublicHooksDripRoute
  ApiPublicHooksLeaderboardBroadcastRoute: typeof ApiPublicHooksLeaderboardBroadcastRoute
  ApiPublicTelegramImportRoute: typeof ApiPublicTelegramImportRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commands': {
      id: '/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof CommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$token': {
      id: '/v/$token'
      path: '/v/$token'
      fullPath: '/v/$token'
      preLoaderRoute: typeof VTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link/$token': {
      id: '/link/$token'
      path: '/link/$token'
      fullPath: '/link/$token'
      preLoaderRoute: typeof LinkTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/import': {
      id: '/api/public/telegram/import'
      path: '/api/public/telegram/import'
      fullPath: '/api/public/telegram/import'
      preLoaderRoute: typeof ApiPublicTelegramImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/leaderboard-broadcast': {
      id: '/api/public/hooks/leaderboard-broadcast'
      path: '/api/public/hooks/leaderboard-broadcast'
      fullPath: '/api/public/hooks/leaderboard-broadcast'
      preLoaderRoute: typeof ApiPublicHooksLeaderboardBroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/drip': {
      id: '/api/public/hooks/drip'
      path: '/api/public/hooks/drip'
      fullPath: '/api/public/hooks/drip'
      preLoaderRoute: typeof ApiPublicHooksDripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/db-export': {
      id: '/api/public/hooks/db-export'
      path: '/api/public/hooks/db-export'
      fullPath: '/api/public/hooks/db-export'
      preLoaderRoute: typeof ApiPublicHooksDbExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/broadcast': {
      id: '/api/public/hooks/broadcast'
      path: '/api/public/hooks/broadcast'
      fullPath: '/api/public/hooks/broadcast'
      preLoaderRoute: typeof ApiPublicHooksBroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/autodelete': {
      id: '/api/public/hooks/autodelete'
      path: '/api/public/hooks/autodelete'
      fullPath: '/api/public/hooks/autodelete'
      preLoaderRoute: typeof ApiPublicHooksAutodeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-backup': {
      id: '/api/public/hooks/auto-backup'
      path: '/api/public/hooks/auto-backup'
      fullPath: '/api/public/hooks/auto-backup'
      preLoaderRoute: typeof ApiPublicHooksAutoBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CommandsRoute: CommandsRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  LinkTokenRoute: LinkTokenRoute,
  VTokenRoute: VTokenRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicHooksAutoBackupRoute: ApiPublicHooksAutoBackupRoute,
  ApiPublicHooksAutodeleteRoute: ApiPublicHooksAutodeleteRoute,
  ApiPublicHooksBroadcastRoute: ApiPublicHooksBroadcastRoute,
  ApiPublicHooksDbExportRoute: ApiPublicHooksDbExportRoute,
  ApiPublicHooksDripRoute: ApiPublicHooksDripRoute,
  ApiPublicHooksLeaderboardBroadcastRoute:
    ApiPublicHooksLeaderboardBroadcastRoute,
  ApiPublicTelegramImportRoute: ApiPublicTelegramImportRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
